mysite/airgeadra/urls.py
from django.urls import path
from . import views
app_name = 'airgeadra'
urlpatterns = [
  #  path('your_url/', views.your_view, name='your_view_name'),
path('', views.index, name='index'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views  # Import your home view
urlpatterns = [
   path('admin/', admin.site.urls),
   path('airgeadra/', include('airgeadra.urls', namespace='airgeadra')),
   path('', views.home, name='home'),  
]

mysite/airgeadra/models.py
from django.db import models

class CurrencyChoice(models.Model):
    email = models.EmailField(primary_key=True)  # Email as primary key
    currency_pair = models.CharField(max_length=10)  # E.g., "EURUSD"
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    buy_or_sell = models.CharField(max_length=5, choices=[
        ('buy', 'Buy'),
        ('sell', 'Sell')
    ])

    def __str__(self):
        return f"{self.email} - {self.currency_pair} ({self.buy_or_sell})"

mysite/airgeadra/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'airgeadra/index.html') 

mysite/mysite/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'mysite/home.html')

mysite/airgeadra/templates/airgeadra/index.html
{% load static %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
<!-- Suggested code may be subject to a license. Learn more: ~LicenseLog:288764885. -->
<!-- Suggested code may be subject to a license. Learn more: ~LicenseLog:2619765851. -->
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
<!-- Suggested code may be subject to a license. Learn more: ~LicenseLog:1101656902. -->
<!-- Suggested code may be subject to a license. Learn more: ~LicenseLog:2509950542. -->
<!-- Suggested code may be subject to a license. Learn more: ~LicenseLog:3503858185. -->
<!-- Suggested code may be subject to a license. Learn more: ~LicenseLog:1195230724. -->
    <link rel="stylesheet" href={% static "css/bootstrap.css" %} />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Currency Exchange Rate App </title>
  </head>
  <body style="overflow:hidden">
    <div class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
      <div class="container">
        <a href="../" class="navbar-brand">Currency Exchange <span style="color: rgb(39, 117, 161);"> <strong>App</strong> </span>   </a>
        <a href="../" class="navbar-tech">[ Vanilla JavaScript ]  </a>
      </div>
    </div>
    
    <br><br><br>
    <div id="jumbotron" class="jumbotron" style="text-align: center; margin-top:-50px">
      <h1 id="devise" class="display-5">Devise </h1>
      <h5>Exchange Rate Converter</h5>
      <img src= {% static 'images/image.jpg' %} class="image" style="width:100px; margin-bottom:-50px; " >
    </div>
    <div class="container">
    <div class="page-header" id="banner">
      <div class="row">
        <div class="col-sm-15">
          <h1 style="align-content: center;"> </h1>
          <p class="lead" style="margin-left:280px; font-size:2rem">
        </p>
        </div>
      </div>
    </div>

  <div class="container">
    <div class="currency">
       <select class="form-control" id="currency-one">
        <option value="AED">AED</option>
        <option value="ARS">ARS</option>
        <option value="AUD">AUD</option>
        <option value="BGN">BGN</option>
        <option value="BRL">BRL</option>
        <option value="BSD">BSD</option>
        <option value="CAD">CAD</option>
        <option value="CHF">CHF</option>
        <option value="CLP">CLP</option>
        <option value="CNY">CNY</option>
        <option value="COP">COP</option>
        <option value="CZK">CZK</option>
        <option value="DKK">DKK</option>
        <option value="DOP">DOP</option>
        <option value="EGP">EGP</option>
        <option value="EUR">EUR</option>
        <option value="FJD">FJD</option>
        <option value="GBP">GBP</option>
        <option value="GTQ">GTQ</option>
        <option value="HKD">HKD</option>
        <option value="HRK">HRK</option>
        <option value="HUF">HUF</option>
        <option value="IDR">IDR</option>
        <option value="ILS">ILS</option>
        <option value="INR">INR</option>
        <option value="ISK">ISK</option>
        <option value="JPY">JPY</option>
        <option value="KRW">KRW</option>
        <option value="KZT">KZT</option>
        <option value="MXN">MXN</option>
        <option value="MYR">MYR</option>
        <option value="NOK">NOK</option>
        <option value="NZD">NZD</option>
        <option value="PAB">PAB</option>
        <option value="PEN">PEN</option>
        <option value="PHP">PHP</option>
        <option value="PKR">PKR</option>
        <option value="PLN">PLN</option>
        <option value="PYG">PYG</option>
        <option value="RON">RON</option>
        <option value="RUB">RUB</option>
        <option value="SAR">SAR</option>
        <option value="SEK">SEK</option>
        <option value="SGD">SGD</option>
        <option value="THB">THB</option>
        <option value="TRY">TRY</option>
        <option value="TWD">TWD</option>
        <option value="UAH">UAH</option>
        <option value="USD" selected>USD</option>
        <option value="UYU">UYU</option>
        <option value="VND">VND</option>
        <option value="ZAR">ZAR</option>
      </select>
    <br>
      <input type="number" id="amount-one"  value="1" style="width:100%" />
    </div>
</div>
<br>
  <div class="swap-btn">
    <button type="button" id="swap" class="btn btn-outline-primary mx-auto d-block" >Swap <i class="fa fa-refresh" aria-hidden="true"></i></button>
  </div>
  <!-- Dynamic rate inserted in DOM based on exchange rate fetched from API -->
  <div class="rate" id="rate"></div>
    <br>
    <div class="container">
      <div class="currency">
         <select class="form-control" id="currency-two">
          <option value="AED">AED</option>
          <option value="ARS">ARS</option>
          <option value="AUD">AUD</option>
          <option value="BGN">BGN</option>
          <option value="BRL">BRL</option>
          <option value="BSD">BSD</option>
          <option value="CAD">CAD</option>
          <option value="CHF">CHF</option>
          <option value="CLP">CLP</option>
          <option value="CNY">CNY</option>
          <option value="COP">COP</option>
          <option value="CZK">CZK</option>
          <option value="DKK">DKK</option>
          <option value="DOP">DOP</option>
          <option value="EGP">EGP</option>
          <option value="EUR">EUR</option>
          <option value="FJD">FJD</option>
          <option value="GBP">GBP</option>
          <option value="GTQ">GTQ</option>
          <option value="HKD">HKD</option>
          <option value="HRK">HRK</option>
          <option value="HUF">HUF</option>
          <option value="IDR">IDR</option>
          <option value="ILS">ILS</option>
          <option value="INR">INR</option>
          <option value="ISK">ISK</option>
          <option value="JPY">JPY</option>
          <option value="KRW">KRW</option>
          <option value="KZT">KZT</option>
          <option value="MXN">MXN</option>
          <option value="MYR">MYR</option>
          <option value="NOK">NOK</option>
          <option value="NZD">NZD</option>
          <option value="PAB">PAB</option>
          <option value="PEN">PEN</option>
          <option value="PHP">PHP</option>
          <option value="PKR">PKR</option>
          <option value="PLN" >PLN</option>
          <option value="PYG">PYG</option>
          <option value="RON">RON</option>
          <option value="RUB">RUB</option>
          <option value="SAR">SAR</option>
          <option value="SEK">SEK</option>
          <option value="SGD">SGD</option>
          <option value="THB">THB</option>
          <option value="TRY">TRY</option>
          <option value="TWD">TWD</option>
          <option value="UAH">UAH</option>
          <option value="USD"selected >USD</option>
          <option value="UYU">UYU</option>
          <option value="VND">VND</option>
          <option value="ZAR">ZAR</option>
        </select>
      <br>
        <input type="number" id="amount-two" placeholder="0" value="1" style="width:100%" />
      </div>
  </div>
  <br>
  <footer id="footer">
    <div class="row">
      <div class="col-lg-12">    
        <p>Code released under the <a href="https://opensource.org/licenses/MIT">MIT License</a>.</p>
      </div>
    </div>

  </footer>

<!-- Suggested code may be subject to a license. Learn more: ~LicenseLog:994087257. -->
  <script src={% static "js/app.js" %}></script>
  </body>
</html>

mysite/mysite/templates/mysite/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href={% static "css/bootstrap.css" %} />
    <title>Fáilte</title>
<!-- ar fáil ó translate.google.com -->
    <script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
    <script type="text/javascript">
        function googleTranslateElementInit() {
            new google.translate.TranslateElement({pageLanguage: 'ga'}, 'google_translate_element');
        }
    </script>
</head>
<body>
    <div id="google_translate_element"></div>

    <h1>Malartú airgeadra</h1>

    <!--<h1><a href="{% url 'airgeadra:index' %}">Téigh</a></h1>-->
    <a href="{% url 'airgeadra:index' %}">Téigh</a>

</body>
</html>